### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [quyse/inanity#25]
I would like to point out that an identifier like “[`___INANITY_STORAGE_HPP___`](https://github.com/quyse/inanity/blob/a39225c5a41f879abe5aa492bb22b500dbe77433/Storage.hpp#L1 "Update candidate")” [does not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by quyse** [comment]
Probably even better to replace header guards with `#pragma once`. But, honestly, there's much worse things to be found with static analyzer here, and this codebase is not actively developed anymore.
